module.exports = {
  darkMode: false,
  theme: {
    screens: {
      xs: '375px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1440px',
      '3xl': '1536px',
    },
    fontFamily: {
      sans: [
        '"proxima-nova"',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
    },
    extend: {
      colors: {
        brand: {
          raspberry: '#C92346',
          sky: '#007AC9',
          dark_blue: '#142C4E',
          denim_blue: '#1056C5',
          yellow: '#FED100',
          light_yellow: '#FFFAE6',
          teal: '#409B74',
          grey: '#383838',
          white: '#FFFFFF',
          rich_black: '#142C4F',
          pastel_sky: '#87B8DB',
          pastel_raspberry: '#DF8DA0',
          pastel_teal: '#88C7B4',
          pastel_aqua: '#ECF6F7',
          pastel_aqua_dark: '#E8F3F4',
          pastel_yellow: '#F8E79A',
          dark_blue_overlay: '#37516E',
          sky_overlay: '#218bd0',
          yellow_overlay: '#fce596',
          teal_overlay: '#66ad92',
        },
      },
    },
  },
};
